AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "sorbet/rbi/**/*"
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 20

Naming/FileName:
  Exclude:
    - "lib/sorbet-concerns.rb"

Naming/BlockForwarding:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Gemspec/DevelopmentDependencies:
  Enabled: false
